name: On Push Make Docs

on: push

env:
    DEVOPS_DIR: devops

permissions:
  actions: read|write
  checks: read|write

jobs:
    create-docs:
        name: Create Docs
        runs-on: ubuntu-latest
        steps:
            - name: Check-out devops repository
              uses: actions/checkout@v3
              with:
                  repository: jq-labs/devops
                  token: ${{ secrets.GITHUB_TOKEN }}
                  path: ${{ env.DEVOPS_DIR }}

            - name: Make Docs
              run: python ${{ env.DEVOPS_DIR }}/script.py ./lib/test.html ./lib/test.md
              shell: sh
