name: On Push Make Docs

on:
    push:
        branches:
            - master
        paths:
            - 'lib/**/*.html'

env:
    DEVOPS_DIR: devops
    AUTHOR: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>

jobs:
    create-docs:
        name: Create Docs
        runs-on: ubuntu-latest
        permissions:
            actions: write
            checks: write
            contents: write
        steps:
            - name: Check-out devops repository
              uses: actions/checkout@v3
              with:
                  repository: jq-play/devops
                  token: ${{ secrets.GITHUB_TOKEN }}
                  path: ${{ env.DEVOPS_DIR }}

            - name: Check-out this repo
              uses: actions/checkout@v3
              with:
                  repository: jq-play/workflow-test
                  path: workflow-test
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Make Docs
              run: python ${{ env.DEVOPS_DIR }}/script.py ./lib/test.html ./lib/test.md
              shell: sh

            # - name: Commit repo
            #   uses: stefanzweifel/git-auto-commit-action@v4
            #   with:
            #       repository: workflow-test
            #       commit_message: Automated Documentations Generated
            #       file_pattern: '**/*.md'

            - name: Commit Repo
              run: |
                  cd workflow-test

                  git config user.name 'github-actions[bot]'
                  git config user.email '41898282+github-actions[bot]@users.noreply.github.com'

                  commit_msg=$(git show --format="%s" HEAD^1 -s)
                  git reset --soft $(git show --format="%h" -s)
                  git add **/*.md
                  git commit -m $commit_msg --author="$AUTHOR"
                  git push

            #   git pull
            #   if [ "$(git show --format="%s" -s)" != "Automated Documentations Generated" ]; then  \
            #     echo "Skipped squashing"; \
            #     exit 0; \
            #   fi
            #   run: |
            #       cd workflow-test
            #       git config --global user.name 'JoshQuaintance'
            #       git config --global user.email 'JoshQuaintance@users.noreply.github.com'
            #       git add **/*.md
            #       git commit
            #       git config pull.rebase false
            #       git pull
            #       git push
