name: On Push Make Docs

on:
    push:
        branches:
            - master

env:
    DEVOPS_DIR: devops

jobs:
    create-docs:
        name: Create Docs
        runs-on: ubuntu-latest
        permissions:
            actions: write
            checks: write
            contents: write
        steps:
            - name: Check-out devops repository
              uses: actions/checkout@v3
              with:
                  repository: jq-play/devops
                  token: ${{ secrets.GITHUB_TOKEN }}
                  path: ${{ env.DEVOPS_DIR }}

            - name: Check-out this repo
              uses: actions/checkout@v3
              with:
                  repository: jq-play/workflow-test
                  path: workflow-test
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Make Docs
              run: python ${{ env.DEVOPS_DIR }}/script.py ./lib/test.html ./lib/test.md
              shell: sh

            - name: Commit repo
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  repository: workflow-test
                  commit_message: Automated Documentations Generated
                  file_pattern: '**/*.md'

            - name: Squash Commit
              run: |
                  cd workflow-test
                  if [ "$(git show --format="%s" -s)" != "Automated Documentations Generated" ]; then  \
                    echo "Skipped squashing"; \
                    exit 0; \
                  fi 
                  commit_msg=$(git show --format="%s" HEAD^1 -s)
                  git reset --soft HEAD~2
                  git commit -m $commit_msg
                  git push
