name: On Push Make Docs

on:
    push:
        branches:
            - master
        paths:
            - 'lib/**/*.html'

env:
    DEVOPS_DIR: devops
    ACTOR_EMAIL: ${{ github.actor }}@users.noreply.github.com
    ACTOR: ${{ github.actor }}

jobs:
    create-docs:
        name: Create Docs
        runs-on: ubuntu-latest
        permissions:
            actions: write
            checks: write
            contents: write
        steps:
            - name: Check-out devops repository
              uses: actions/checkout@v3
              with:
                  repository: jq-play/devops
                  token: ${{ secrets.GITHUB_TOKEN }}
                  path: ${{ env.DEVOPS_DIR }}

            - name: Check-out this repo
              uses: actions/checkout@v3
              with:
                  repository: jq-play/workflow-test
                  path: workflow-test
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Make Docs
              run: python ${{ env.DEVOPS_DIR }}/script.py ./lib/test.html ./lib/test.md
              shell: sh

            - name: Commit Repo
              run: |
                  cd workflow-test

                  git config user.name "$ACTOR"
                  git config user.email "$ACTOR_EMAIL"

                  commit_msg=$(git show --format="%s" -s)
                  git reset --soft $(git show --format="%h" -s)
                  git add **/*.md
                  git commit -m $commit_msg --author="$AUTHOR"
                  git push

