name: On Push Make Docs

on:
    push:
        branches:
            - master

env:
    DEVOPS_DIR: devops

jobs:
    create-docs:
        name: Create Docs
        runs-on: ubuntu-latest
        permissions:
            actions: write
            checks: write
        steps:
            - name: Check-out devops repository
              uses: actions/checkout@v3
              with:
                  repository: jq-play/devops
                  token: ${{ secrets.GITHUB_TOKEN }}
                  path: ${{ env.DEVOPS_DIR }}

            - name: Check-out this repo
              uses: actions/checkout@v3
              with:
                  repository: jq-play/workflow-test
                  path: workflow-test
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Make Docs
              run: python ${{ env.DEVOPS_DIR }}/script.py ./lib/test.html ./lib/test.md
              shell: sh

            - name: Commit repo
              run: |
                  cd workflow-test
                  git config --global user.name 'JoshQuaintance'
                  git config --global user.email 'JoshQuaintance@users.noreply.github.com'
                  git status
                  git add **/*.md
                  git commit -am "Automated Docs"
                  git push
