name: On Push Make Docs

on:
    push:
        branches:
            - master

env:
    DEVOPS_DIR: devops

jobs:
    create-docs:
        name: Create Docs
        runs-on: ubuntu-latest
        permissions:
            actions: write
            checks: write
        steps:
            - name: Check-out devops repository
              uses: actions/checkout@v3
              with:
                  repository: jq-labs/devops
                  token: ${{ secrets.GITHUB_TOKEN }}
                  path: ${{ env.DEVOPS_DIR }}

            - name: Make Docs
              run: python ${{ env.DEVOPS_DIR }}/script.py ./lib/test.html ./lib/test.md
              shell: sh
